### PR TITLE
Pc m23-9am-3 Rider Application Pages

### PR DESCRIPTION
**Pull request by pconrad**
This PR is originally from @Kanagawa-okiNamiUra as part of https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-3/pull/44

---

In this PR, I implemented Index/Create/EditPage for Rider Application from Member's View (in the nav bar "Apply to be a rider." I also added a placeholder nav bar for admin's view.

Notice that this PR does not address not the fourth issue in the instruction because the show page, where fields not disabled in the form should be read only. I could not figure out how to do that other than writing a new Table component, which could be demanding considering the time I had. For now, the show button in the table will lead to the edit page, which is very similar to what it is supposed to look like.

Running Instance at: https://gride-albert-dev.dokku-03.cs.ucsb.edu/

An implementation note is that we (who have both ROLE_ADMIN and ROLE_MEMBER) will only have ROLE_MEMBER when we open the Index page. This is achieved by creating a copy of currentUser and modify the copy for easier reuse of the table component. In reality, it would not be a problem for users and we admins are barely affected. A picture explanation is attached below.
image
- Notice the Admin field disappears when we are at the URL /apply/rider.
image
- When we are no longer on that page, we're admins again. (The admins field appears in the picture above)

Some more screenshots of the app:
image
image

### CODE REVIEW

**Comment by Mohamed-Elfouly** [comment]
Immediate issue solved. Check that in apps.js and navbar if we have the desired functionality.

**Review by Aasish-Virjala — APPROVED** [review]
Looks good to me, but one question/statement. It is showing that there are files that are changed, but only additions were made (no deletions). However, these files are already in main, and this is an identical copy of it. Was anything changed in these files or are they just getting committed now, I am a little confused. For reference, check the changelog for this PR, specifically these files: 


frontend/src/stories/components/RiderApplication/RiderApplicationTable.stories.js
frontend/src/main/utils/riderApplicationUtils.js
frontend/src/main/pages/RiderApplication/RiderApplicationIndexPageMember.js
frontend/src/main/pages/RiderApplication/RiderApplicationCreatePage.js
frontend/src/stories/components/RiderApplication/RiderApplicationTable.stories.js

**Comment by Mohamed-Elfouly** [comment]
Thank you for bringing this to my attention, I did not realize this was occurring. I will look into it and try to fix it as soon as possible.

**Comment by Mohamed-Elfouly** [comment]
I just looked, and these files are not in main, or at least they don't appear to be in main.

**Pull request merged**
